spring:
  profiles:
    active: dev
  session:
    store-type: none
  application:
    name: supersoft-consumer
  cache:
    type: redis
  thymeleaf:
    cache: false
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss

swaggerVersion: 1.0
logging:
  config: classpath:config/logback-spring.xml
server:
  port: 8082
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
  context-path:

supersoft:
  static-path: http://localhost/
  context-path: http://localhost:${server.port}${server.context-path}
---
#development profile
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # Redis数据库索引（默认为0）
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekauser:123456@localhost:8761/eureka  #注册 中心已经开启认证
  instance:
     leaseRenewalIntervalInSeconds: 5 # 续约更新时间间隔（默认30秒）
     leaseExpirationDurationInSeconds: 10 # 续约到期时间（默认90秒）

swagger:
    doc-version: ${swaggerVersion}
    enabled: true

kaptcha:
  session:
    key: kaptcha.code
  border: yes
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
  obscurificator:
    impl: com.google.code.kaptcha.impl.WaterRipple
  #不要噪点
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
  image:
    width: 90
    height: 33
  textproducer:
    font:
      size: 25
      color: black
    char:
      length: 4
      space: 5
  #和登录框背景颜色一致
  background:
    clear:
      from: 247,247,247
      to: 247,247,247


management:
  security:
    enabled: false